### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mpkuchera** [ML4SCI/DeepFalcon#5]
Please leave information in your readme, such as: dependencies needed, how to run code, repo structure, etc.

**Comment by mpkuchera** [comment]
^^ For the main landing page. The documentation in each folder is strong.

**Comment by emanueleusai** [comment]
@mpkuchera Thank you very much for reviewing the repository!
@adiah80 @ahariri13 could you please take care of this?

**Comment by dbmohit** [comment]
Can i work on this?

**Comment by AtrikeshM** [comment]
I want to work on this issue. Please assign me.
